cognitive-complexity-threshold = 30
type-complexity-threshold = 250

max-suggested-slice-pattern-length = 3
single-char-binding-names-threshold = 4

vec-box-size-threshold = 4096
trivial-copy-size-limit = 128

enum-variant-name-threshold = 3
literal-representation-threshold = 10
